#pragma once

#define KB_MAPSIZE 128

typedef char KB_KEY;

enum KB_SPECIALKEY {
  KB_SPECIALKEY_BACKSPACE='\b',
  KB_SPECIALKEY_TAB='\t',
  KB_SPECIALKEY_NONE=-128,
  KB_SPECIALKEY_ESC,
  KB_SPECIALKEY_ENTER,
  KB_SPECIALKEY_ENTERKP,
  KB_SPECIALKEY_INT2,
  KB_SPECIALKEY_LCTRL,
  KB_SPECIALKEY_LSHIFT,
  KB_SPECIALKEY_RCTRL,
  KB_SPECIALKEY_RSHIFT,
  KB_SPECIALKEY_ALT,
  KB_SPECIALKEY_CAPSLCK,
  KB_SPECIALKEY_F1,
  KB_SPECIALKEY_F2,
  KB_SPECIALKEY_F3,
  KB_SPECIALKEY_F4,
  KB_SPECIALKEY_F5,
  KB_SPECIALKEY_F6,
  KB_SPECIALKEY_F7,
  KB_SPECIALKEY_F8,
  KB_SPECIALKEY_F9,
  KB_SPECIALKEY_F10,
  KB_SPECIALKEY_NUMLCK,
  KB_SPECIALKEY_SCRLLCK,
  KB_SPECIALKEY_HOME,
  KB_SPECIALKEY_UPARROW,
  KB_SPECIALKEY_PAGEUP,
  KB_SPECIALKEY_LEFTARROW,
  KB_SPECIALKEY_DOWNARROW,
  KB_SPECIALKEY_PAGEDOWN,
  KB_SPECIALKEY_END,
  KB_SPECIALKEY_RIGHTARROW,
  KB_SPECIALKEY_INSERT,
  KB_SPECIALKEY_DELETE,
  KB_SPECIALKEY_F11,
  KB_SPECIALKEY_F12,
  KB_SPECIALKEY_FWSLASHKP,

  KB_SPECIALKEY_LAST
};
CASSERT(KB_SPECIALKEY_LAST < 0);

enum KB_LAYOUT {
  KB_LAYOUT_NONE=-1,
  KB_LAYOUT_US,

  KB_LAYOUT_COUNT
};

KB_KEY MapKeystroke(int ixKey, KB_LAYOUT eLayout);
